name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: On my_custom_webhook do ABC...
      env:
        LAST_HIT_CI_PARAMS: ${{ toJson(github.event.client_payload) }}
      if: github.event.action == 'LAST_HIT_CI'
      run: |
        echo "Hello From my_custom_webhook...doing ABC"
        echo "$LAST_HIT_CI_PARAMS"
